- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
#        msg: "Hello LoicA!"
        msg: "Cost Center: {{ cost_center }} Project ID: {{project_id}} "
#    - name: Print all available facts
#      debug:
#        var: ansible_facts
#        var: vars
