- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
#       msg: "Hello LoicA!"
        msg: "number of Cpus: {{ cpu }} Var from prompt: {{ var1 }} " 
#    - name: Print all available facts
#      debug:
#        var: ansible_facts
#        var: vars
