- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello LoicA! {{ ansible_facts['nodename'] }}"
    - name: Print all available facts
      debug:
        var: ansible_facts
