- name: Hello World Sample
  hosts: all

  vars:
#   my_message: "Hello Loic"
    my_message: "{{ test }}" 
    
  tasks:
#    - name: Apply facts
#      ansible.builtin.set_fact:
#        update: "loic"
        
    - name: Hello Message
      debug:
        msg: "{{my_message}} {{update}}"

    - name: Record deployment metadata
      ansible.builtin.set_stats:
        data:
          update: loic
        per_host: false
        aggregate: true
      

        
     # msg: "{{ cost_center }}" 
#  - name: Print all available facts
#     debug:
#       var: ansible_facts
#       var: vars
