- name: Hello World Sample
  hosts: all

  vars:
#   my_message: "Hello Loic"
    my_message: "{{ test }}" 
    
  tasks:
    - name: Hello Message
      debug:
        msg: "{{my_message}}"
    - name: Apply facts
      ansible.builtin.set_fact:
        update: "loic"
        
     # msg: "{{ cost_center }}" 
#  - name: Print all available facts
#     debug:
#       var: ansible_facts
#       var: vars
