- name: Hello World Sample
  hosts: all

  vars:
#   my_message: "Hello Loic"
#   my_message: "{{ test }}" 
    
  tasks:
    - name: Apply defaults
      ansible.builtin.set_fact:
        my_message: "{{ test | default('unknown') }}"
        
    - name: Hello Message
      debug:
        msg: "{{my_message}}"
     # msg: "{{ cost_center }}" 
#  - name: Print all available facts
#     debug:
#       var: ansible_facts
#       var: vars
