- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello LoicA! {{answer}} to {{project}}"
    - name: Print all available facts
      debug:
        var: ansible_facts
